services:
    telegram.command.default:
        alias: App\Command\ByDefault\v1
        public: true

    telegram.command.process.send.message:
        alias: App\Command\Process\SendMessageCommands
        public: true

    telegram.command.process.callback.message:
        alias: App\Command\Process\CallbackMessageCommands
        public: true

    #action commands
    telegram.action.command.send.message:
        alias: App\Command\ActionCommand\Commands\SendLayout
        public: true

    telegram.action.command.edit.message:
        alias: App\Command\ActionCommand\Commands\EditLayout
        public: true

    telegram.action.command.add.item:
        alias: App\Command\ActionCommand\Commands\AddItem
        public: true

    telegram.action.command.remove.item:
        alias: App\Command\ActionCommand\Commands\RemoveItem
        public: true
