monolog:
    handlers:
        stream:
            type: stream
            path: "%kernel.logs_dir%/debug.log"
            level: debug
            channels: ["!event"]

        error_log:
            type: stream
            path: "%kernel.logs_dir%/errors.log"
            level: error
            channels: ["!event"]

        critical_log:
            type: stream
            path: "%kernel.logs_dir%/critical.log"
            level: critical

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
